# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d5713870e52993dc76f9a1f83e5b0fa32921fb4346ed52c1f33e57b8fcf81213f0444891adcde1819cfa6e0efc2fed867fd4e51599e74cde2cf7810eb4d6dac

test:
  secret_key_base: 890dcbc20110c542935b899f199a0d679b15b07205c646c9d4d5a2635fb0d695bb17f44f70ef987847ecdbc811a5cede25e670b1c89f7020d32ece98de91e753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
